disabled_rules: # rule identifiers to exclude from running
  - line_length
  - type_body_length
  - large_tuple
  - switch_case_alignment
  - function_parameter_count
  - implicit_getter
  - trailing_whitespace
  - multiple_closures_with_trailing_closure

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

opt_in_rules:
  - weak_delegate
  - vertical_whitespace
# Force cast
force_cast: error
force_try:
  severity: warning

nesting:
  type_level: 3

# File length
file_length:
  warning: 700
  error: 1200

cyclomatic_complexity:
    warning: 18 # 18 nested ifs are acceptable
    error: 20 # 20 nested ifs shows warning, 11 causes compile error
