# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :sanity_check do
    # Testing
    scan(
      workspace: "CICDSample.xcworkspace",
      devices: ["iPhone 11"],
      scheme: "CICDSample-REC",
      open_report: false,
      code_coverage: true, # important for slather !
      skip_build: false,
      skip_slack: false,
      clean: true)
    # Linting
    swiftlint(
      raise_if_swiftlint_error: true,
			output_file: "reports/swiftlint.txt",
			ignore_exit_status: true,
			config_file: ".swiftlint.yml")
    # Coverage
    slather(
      use_bundle_exec: true,
      sonarqube_xml: true,
      cobertura_xml: true,
      teamcity: true,
      scheme: "CICDSample-REC",
      output_directory: "reports/",
      proj: "CICDSample.xcodeproj",
      workspace: "CICDSample.xcworkspace",
      ignore: ["Pods/\*\*"]
      )
    # Rename File
    sh("cd .. && mv reports/cobertura.xml reports/coverage-swift.xml")
    # Complexity
    lizard(
  		source_folder: "CXPMobile",
  		language: "swift",
  		export_type: "xml",
  		report_file: "reports/lizard-report.xml")
    sonar
  end

  lane :sos do
    sonar
  end
end
