# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :sanity_check do
    # Testing
    scan(
      workspace: "CICDSample.xcworkspace",
      devices: ["iPhone 11"],
      open_report: false,
      code_coverage: true, # important for slather !
      skip_build: false,
      skip_slack: false,
      clean: true)
    # Linting
    swiftlint(
      raise_if_swiftlint_error: true,
			output_file: "fastlane/reports/swiftlint.txt",
			ignore_exit_status: true,
			config_file: ".swiftlint.yml")
  end
end
